version: "3.1"
services:
  php:
    image: php:8.0-fpm-alpine
    restart: on-failure
    expose:
      - "9000"
    networks:
      - backend
    volumes:
      - ./api:/data/www:Z
#      - ./php:/usr/local/etc/php/php.ini

  nginx:
    build: ./
    image: qsave_client
    restart: on-failure
    environment:
      TEST: mongodb://root:example@mongo:27017/admin
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z
    ports:
      - "8080:80"
    depends_on:
      - php

networks:
  backend:
