name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Primes
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.hello
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}-${{ hashFiles('**/docker-compose.*') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: load docker cache
        run: |
          docker load -i ~/.hello/nginx.tar || true
          docker load -i ~/.hello/node.tar || true
          docker load -i ~/.hello/php.tar || true

      - name: docker-compose up
        run: |
          docker-compose up --build --remove-orphans --detach
          sleep 10

      - name: curl /
        run: |
          curl --location --request GET 'http://localhost:8081'

      - name: docker-compose down
        run: |
          docker-compose down

      - name: save docker cache
        run: |
          mkdir -p ~/.hello
          rm -rf *.tar
          docker save -o ~/.hello/nginx.tar nginx:1.21-alpine
          docker save -o ~/.hello/node.tar node:14.17-alpine
          docker save -o ~/.hello/php.tar php:8.0-fpm-alpine
