name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: docker compose up
        run: |
          docker compose up --build --remove-orphans --detach
          sleep 10

      - name: curl /
        run: |
          curl --head --location --silent --fail --request GET 'http://localhost:8081'
          sleep 1

      - name: curl /api/qnotes
        run: |
          curl --head --location --silent --fail --request GET 'http://localhost:8081/api/qnotes'
          sleep 1

      - name: docker compose down
        run: |
          docker compose down -v

